name: "CI"

on: [push, pull_request]

jobs:

  server:
    strategy:
      matrix:
        python-version: ['3.10']
    uses: superdesk/superdesk/.github/workflows/server.yml@develop
    with:
      python-version: ${{ matrix.python-version }}
  
  pytest:
    strategy:
      matrix:
        python-version: ['3.10']
    uses: superdesk/superdesk/.github/workflows/pytest.yml@develop
    with:
      python-version:  ${{ matrix.python-version }}
  
  client:
    strategy:
      matrix:
        node-version: ['22']
    uses: superdesk/superdesk/.github/workflows/client.yml@develop
    with:
      node-version:  ${{ matrix.node-version }}